### ISSUE TITLE
Redis adapter's `collection` method does not return a promise

### ISSUE THREAD

**Issue by PandaWhisperer** [pandastrike/pirate#27]
I just noticed that [the Redis adapter's `collection` method does not return a promise][1]. That's not really a big deal when using it with `yield`, but for someone who might be using it from plain old JS it might be confusing to get a promise sometimes, and sometimes not.

This is probably my fault, because I ported the Redis adapter. 

[1]: https://github.com/pandastrike/pirate/blob/es6/src/redis-adapter.coffee#L42-L45

**Comment by dyoder** [comment]
The idea of Pirate is to provide a normalized interface regardless of the backing store.

Since, in some cases, returning a collection will be an asynchronous operation, the interface should always return a promise.

**Comment by PandaWhisperer** [comment]
Closed via #28.
